

export default function ButtonPad( { handler } ) 
{

    return (
        <div 
            className="square"
            style={gridStyle}
        >
            <button 
            className="C"
            style={specialStyle}
            onClick={handler}
            >
                C
            </button>
            <button 
            style={specialStyle}
            onClick={onPlusMinus}
            >+/-
            </button>
            <button 
            style={specialStyle}
            onClick={onPercent}
            >%
            </button>
            <button 
            style={handlerStyle}
            onClick={onDivide}
            >÷</button>
            <button 
            style={handlerStyle}
            onClick={onSeven}
            >7</button>
            <button 
            style={handlerStyle}
            onClick={onEight}
            >8</button>
            <button 
            style={handlerStyle}
            onClick={onNine}
            >9</button>
            <button 
            style={handlerStyle}
            onClick={onMultiply}
            >x</button>
            <button 
            style={handlerStyle}
            onClick={onFour}
            >4</button>
            <button 
            style={handlerStyle}
            onClick={onFive}
            >5</button>
            <button 
            style={handlerStyle}
            onClick={onSix}
            >6</button>
            <button 
            style={handlerStyle}
            onClick={onMinus}
            >-</button>
            <button 
            style={handlerStyle}
            onClick={onOne}
            >1</button>
            <button 
            style={handlerStyle}
            onClick={onTwo}
            >2</button>
            <button 
            style={handlerStyle}
            onClick={onThree}
            >3</button>
            <button 
            style={handlerStyle}
            onClick={onPlus}
            >+</button>
            <button 
            style={handlerStyle}
            onClick={onZero}
            >0</button>
            <button 
            style={handlerStyle}
            onClick={onDel}
            >Del</button>
            <button 
            style={buttonStyle}
            onClick={onDot}
            >.</button>
            <button 
            style={handlerStyle}
            onClick={onEqual}
            >=</button>
        </div>
    )
}